## Bài tập với thư viện numpy

1. Tạo dãy a chứa 12 số: 1, 2, 3, ..., 12 

In [21]:
import numpy as np          #sử dụng thư viện numpy với tên np 
a = np.arange(1, 13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


2. Tạo ma trận table 3x4 được lấp đầy bằng các số của a theo trình tự từ trên xuống dưới, từ trái qua phải

In [22]:
table = a.reshape((3, 4))
print(a, '\n\n', table)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Tạo mảng a2 với các số lấy từ những cột chẵn của table

In [16]:
a2 = table[:,::2].reshape(6)
print(a2)

[ 1  3  5  7  9 11]


    Cần lưu ý gì khi thực hiện:

In [18]:
a2[4] = 1000

    giá trị của table[0, 2] sẽ bị thay đổi

In [19]:
print(table)

[[   1    2    3    4]
 [   5    6    7    8]
 [1000   10   11   12]]


    Muốn table không đổi khi thay đổi a2 thì phải làm gì ???

4. Tạo table2 bằng cách "nhân đôi" table theo chiều dọc

In [23]:
table2 = np.concatenate([table, table])
print(table2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5. Tạo table3 bằng cách "nhân đôi" table theo chiều ngang

In [24]:
table3 = np.concatenate([table, table], axis=1)
print(table3)

[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


6. Ghi bảng table ra tập tin văn bản table.txt

In [27]:
np.savetxt('table.txt', table, fmt='%4d')

7. Đọc ma trận T từ tập tin văn bản table.txt

In [30]:
T = np.loadtxt('table.txt', dtype='int')
print(T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Bài tập về nhà

1. Tạo bảng T kích thước 5x4 gồm các số được tạo ngẫu nhiên trong đoạn [-1000..1000]
2. Tìm dòng có giá trị lớn nhất là nhỏ nhất trong tất cả các dòng
3. Tìm cột có giá trị trung bình cao nhất
2. Tạo bảng T1 là chuyển vị của T
6. Thêm 1 cột chứa các giá trị ngẫu nhiên vào bên trái T
7. Thêm 1 dòng chứa các giá trị ngẫu nhiên vào bên trên T
8. Đặt tất cả giá trị trên cột 3 của T đều bằng 0
9. Tăng tất cả giá trị trên dòng 2 của T lên 10 đơn vị